name: Node CI

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  AtmoPack-Vanilla_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pack
        uses: actions/checkout@v3
      - name: node index
        run: |
          npm ci
          node index
      - name: AtmoPack-Vanilla
        uses: actions/upload-artifact@v3
        with:
          name: AtmoPack-Vanilla
          path: AtmoPack-Vanilla.zip
      - name: Create Github Release
        uses : action/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{ github.run_number}}
         release_name: Release ${{ github.run.number }}
      - name: Upload Release asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: ${{ setps.create-new-release.outputs.upload_url }}
         asset_path: ./AtmoPack-Vanilla.zip
         asset_name: AtmoPack-Vanilla-v${{ github.run.number }}.zip
         asset_content_type: application/zip
