name: Node CI

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  AtmoPack-Vanilla_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pack
        uses: actions/checkout@v3
      - name: node index
        run: |
          npm ci
          node index
      - name: AtmoPack-Vanilla
        uses: actions/upload-artifact@v3
        with:
          name: AtmoPack-Vanilla
          path: AtmoPack-Vanilla.zip 
      - name: Validate and extract release information
        id: release
        uses: manovotny/github-releases-for-automated-package-publishing-action@v1.0.0

        # This will publish a version of a package.
      - name: Publish version
        if: steps.release.outputs.tag == ''
        run: yarn publish --new-version ${{ steps.release.outputs.version }}
        env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
